import Head from "next/head";
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import memoji from "../public/memoji.jpg";
import tabogo from "../public/tabogo.jpg";
import rocket from "../public/rocket.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Eric Ramirez</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#contact"
                >
                  contact me
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Eric Ramirez
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              systems engineer and Web developer!
            </h3>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/fabianra5789">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/eric-fabian-ramirez-aguilar-8b0063230/">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/eric_ramireza_/">
                <AiFillInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={memoji} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section></section>
        <section className="py-10" id="portfolio">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portofolio</h3>
          </div>
          <div className="flex flex-wrap justify-center">
            <div className="max-w-sm rounded overflow-hidden shadow-lg m-4">
              <div className="relative">
                <Image
                  src={tabogo}
                  alt="TABOGO"
                  layout="responsive"
                  width={700}
                  height={475}
                />
              </div>
              <div className="px-6 py-4">
                <div className="font-bold text-xl mb-2">Tabogo Live</div>
                <p className="text-gray-700 text-base">
                  Full Stack Reservations.
                </p>
              </div>
              <div className="px-6 pt-4 pb-2">
                <a
                  href="https://tabogo.vercel.app/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-full mr-2"
                >
                  Ver proyecto
                </a>
                <a
                  href="https://github.com/fabianra5789/NightlifeHub"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-full"
                >
                  Repositorio
                </a>
              </div>
            </div>
            <div className="max-w-sm rounded overflow-hidden shadow-lg m-4">
              <div className="relative">
                <Image
                  src={rocket}
                  alt="rocket"
                  layout="responsive"
                  width={700}
                  height={475}
                />
              </div>
              <div className="px-6 py-4">
                <div className="font-bold text-xl mb-2">RocketSphere</div>
                <p className="text-gray-700 text-base">
                  Full Stack Clone Twitter(X).
                </p>
              </div>
              <div className="px-6 pt-4 pb-2">
                <a
                  href="https://rocketsphere.netlify.app/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-full mr-2"
                >
                  Ver proyecto
                </a>
                <a
                  href="https://github.com/fabianra5789/RocketSphere"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-full"
                >
                  Repositorio
                </a>
              </div>
            </div>
            {/* Agrega más tarjetas para más proyectos si es necesario */}
          </div>
        </section>
      </main>
    </div>
  );
}
